"""hidden field

Revision ID: a48cd4f781dc
Revises: 756d34e8f2a1
Create Date: 2022-12-13 21:04:54.959079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48cd4f781dc'
down_revision = '756d34e8f2a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('hidden', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_images_hidden'), 'images', ['hidden'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_hidden'), table_name='images')
    op.drop_column('images', 'hidden')
    # ### end Alembic commands ###
