"""sha1_sum

Revision ID: 39c96235f9aa
Revises: 90104e3d3ebc
Create Date: 2022-12-14 00:42:20.442592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c96235f9aa'
down_revision = 'a48cd4f781dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('sha1_hash', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_images_sha1_hash'), 'images', ['sha1_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_sha1_hash'), table_name='images')
    op.drop_column('images', 'sha1_hash')
    # ### end Alembic commands ###
