"""add extra_count

Revision ID: 6edfb5ff0a1c
Revises: 39c96235f9aa
Create Date: 2023-02-01 23:20:45.550837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edfb5ff0a1c'
down_revision = '39c96235f9aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('extra_count', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_images_extra_count'), 'images', ['extra_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_extra_count'), table_name='images')
    op.drop_column('images', 'extra_count')
    # ### end Alembic commands ###
